
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    error_log  logs/error.log  notice;
    access_log logs/access.log;
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # ===============================
    # Lua runtime environment
    # ===============================
    lua_package_path "/usr/local/openresty/nginx/lua/?.lua;/usr/local/openresty/site/lualib/?.lua;/usr/local/openresty/lualib/?.lua;/usr/share/lua/5.1/?.lua;;";
    lua_shared_dict cmcd_cfg 1m;

    # ===============================
    # Put collector URL into shared dict
    # ===============================    
    init_by_lua_block {
        local dict = ngx.shared.cmcd_cfg
        dict:set("cmcd_collector_url", "http://10.64.39.13:3000/cmcd/response-mode")
    }

    init_worker_by_lua_block {
        package.loaded["cmcd_response_json"] = nil
        cmcdHandle = require "cmcd_response_json"
        ngx.log(ngx.ERR, "[cmcd] init_worker type=", type(cmcdHandle))
    }

    server {
        listen 0.0.0.0:8088;
        server_name localhost;
    
        access_log  logs/access.log;
    
        #Server-level rewrite phase: executed for all requests handled by this server block
        rewrite_by_lua_block {
            ngx.log(ngx.ERR, "SERVER REWRITE HIT v0.4: ", ngx.var.request_uri)
            
            local p = package.searchpath("cmcd_response_json", package.path)
            ngx.log(ngx.ERR, "[cmcd] resolved file=", p or "nil")

            local m = require "cmcd_response_json"
            ngx.log(ngx.ERR, "[cmcd] module type=", type(m))
        }
    
        # ===============================
        # CMCD → event-mode JSON
        # ===============================
        location ^~ /media/ {
        	rewrite_by_lua_block {
        		ngx.log(ngx.ERR, "INLINE REWRITE HIT v0.4: ", ngx.var.request_uri)
                cmcdHandle.handle()
        	}
        		
        	content_by_lua_block {
                ngx.exit(204)
            }
        }
    
        location / {
            root   html;
            index  index.html index.htm;
        }
    
        error_page   500 502 503 504  /50x.html;
        location = /50x.html { root html; }
    }
}
