
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    error_log  logs/error.log  notice;
    access_log logs/access.log;
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # ===============================
    # Lua runtime environment
    # ===============================
    lua_package_path "/usr/local/openresty/site/lualib/?.lua;/usr/local/openresty/lualib/?.lua;/usr/share/lua/5.1/?.lua;;";
    lua_shared_dict cmcd_cfg 1m;

    # ===============================
    # Put collector URL into shared dict
    # ===============================
    init_by_lua_block {
        local dict = ngx.shared.cmcd_cfg
        dict:set("collector_event_url", "http://10.64.39.13:3000/cmcd/response-mode")
    }

    server {
        listen 0.0.0.0:8088;
        server_name localhost;
    
        access_log  logs/access.log;
    
        # ① Server级rewrite：对这个server的所有请求都会执行
        rewrite_by_lua_block {
            ngx.log(ngx.ERR, "SERVER REWRITE HIT: ", ngx.var.request_uri)
        }
    
        # ===============================
        # CMCD → event-mode JSON
        # ===============================
        location ^~ /media/ {
        	rewrite_by_lua_block {
        		ngx.log(ngx.ERR, "INLINE REWRITE HIT: ", ngx.var.request_uri)
        		dofile("/usr/local/openresty/nginx/lua/cmcd_response_json.lua")
        		}
        		
        	content_by_lua_block {
                ngx.exit(204)
            }
        }
    
        # ③（可选兜底）在log阶段再打一次，若rewrite完全没跑，此处也会打印
        log_by_lua_block {
            ngx.log(ngx.ERR, "LOG PHASE HIT: ", ngx.var.request_uri)
        }
    
        location / {
            root   html;
            index  index.html index.htm;
        }
    
        error_page   500 502 503 504  /50x.html;
        location = /50x.html { root html; }
    }
}
