# flake8: noqa

"""
    M1_ContentHostingProvisioning

    5GMS AF M1 Content Hosting Provisioning API © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.   # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from rt_5gms_as.openapi_5g.api_client import ApiClient

# import Configuration
from rt_5gms_as.openapi_5g.configuration import Configuration

# import exceptions
from rt_5gms_as.openapi_5g.exceptions import OpenApiException
from rt_5gms_as.openapi_5g.exceptions import ApiAttributeError
from rt_5gms_as.openapi_5g.exceptions import ApiTypeError
from rt_5gms_as.openapi_5g.exceptions import ApiValueError
from rt_5gms_as.openapi_5g.exceptions import ApiKeyError
from rt_5gms_as.openapi_5g.exceptions import ApiException
