#!/usr/bin/python3
#
# 5G-MAG Reference Tools: 5GMS Application Server
# ===============================================
#
# File: tests/test_openresty_server_config.py
# License: 5G-MAG Public License (v1.0)
# Author: Sukrit Gupta <sukrit.gupta@dolby.com>
# Copyright: (C) 2026 Dolby Laboratories Inc.
#
# For full license terms please see the LICENSE file distributed with this
# program. If this file is missing then the license can be retrieved from
# https://drive.google.com/file/d/1cinCiA778IErENZ3JN52VFW-1ffHpx7Z/view
#
# [Gen-AI-Assisted]: This file contains code generated by an AI assistant.
#
'''Tests for the nginx server blocks generated by OpenRestyServerConfig.

Run with: python3 -m unittest discover -s tests
'''

import asyncio
import logging
import tempfile
import unittest

from rt_5gms_as.proxies.openresty import OpenRestyServerConfig


class _StubContext:
    def getConfigVar(self, section, key):
        return {'http_port': '80', 'https_port': '443'}[key]

    def appLog(self):
        return logging.getLogger(__name__)


class OpenRestyServerConfigTest(unittest.TestCase):
    def setUp(self):
        self._docroot = tempfile.TemporaryDirectory()
        self.addCleanup(self._docroot.cleanup)

    def _render(self, certfile=None):
        server = OpenRestyServerConfig(_StubContext(), {'as.example.com'}, certfile=certfile, docroot=self._docroot.name)
        return asyncio.run(server.config())

    def test_tls_server_enables_http2(self):
        config = self._render(certfile='/var/cache/rt-5gms/as/certificates/cert-1')
        self.assertIn('listen 443 ssl;', config)
        self.assertIn('http2 on;', config)

    def test_plain_http_server_does_not_enable_http2(self):
        config = self._render()
        self.assertIn('listen 80;', config)
        self.assertNotIn('http2', config)


if __name__ == '__main__':
    unittest.main()
