name: Build Application Server

on:
  push:
    branches: [ development ]
  schedule:
    - cron: '0 0 * * 0' # Executes every Sunday at midnight UT
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        check-latest: true
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install wget default-jdk
        python -m pip install --upgrade pip build setuptools
    - name: Install OpenResty
      uses: leafo/gh-actions-openresty@v1
      with:
        buildCache: true
    - name: Add OpenResty to PATH
      run: |
        PATH="/usr/local/openresty/nginx/sbin:$PATH" export PATH
    - name: Build package
      run: python3 -m pip install .
    - name: Run Application Server
      run: |
        5gms-application-server -h


